start:
  name: Start Wolt Watch
  description: Watch a Wolt restaurant and notify when it opens.
  fields:
    slug:
      name: Restaurant Slug
      description: The Wolt restaurant identifier (e.g., "taizu", "mcdonalds-dizengoff")
      required: true
      example: "taizu"
      selector:
        text:
    timeout_m:
      name: Watch Duration
      description: How long to watch the restaurant (in minutes)
      required: false
      default: 30
      example: 30
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: "minutes"
          mode: "box"
    device:
      name: Notification Device
      description: The notify service to send notifications to (e.g., "notify.mobile_app_iphone")
      required: true
      example: "notify.mobile_app_iphone"
      selector:
        entity:
          domain: notify
          integration: mobile_app